apiVersion: v1
kind: ConfigMap
metadata:
  name: external-secrets-verify-script
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/hook: PostSync
data:
{{- (.Files.Glob "scripts/*").AsConfig | nindent 2 }}
